<!DOCTYPE html>
<html lang='en'>

	<head>
	
		<title> Shells Demo </title>
		<meta charset='utf-8'>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
		
		<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet">

		<style>

			.myimg {
				display:block;
				margin-top:2em;
			}

		</style>

	</head>

	<body>
		<div class='container'>
			<div class='jumbotron' style='margin-top:2em;'>
				<h1 class='display-3'>Shell Model Demo</h1>
			</div>

			<div class='row'>
				<div class='col-xs-12'>
					<h1>Background - Important</h1>

					<p>So far we have investigated the mass and stability of nuclei, now we want to explore the structure of the nucleus in more details. We understand the effects of the mass number $A$ and the number of protons and neutrons $Z$ and $N$ on the strength of the binding of the nuclei but when we look at the energy it takes to excite nuclei to their first excited state we see that the largest excitation energies are concentrated around specific values of $N$ and $Z$, see below.</p>

					<img src='whatever' alt='figure' width='100%'>

					<p>These numbers are called "magic" numbers. The shell model can explain these numbers. We already observed that the binding energy per nucleon had enhancements around the places corresponding to one of the proton or neutron number close to a magic number.</p>

					<p>For the shell model we consider a nucleon moving in the potential generated by the other nucleons. The potential will have discrete energy levels and since the nucleons are fermions there will be at most two nucleons in the same state. Since protons and neutrons are different fermion this limitation is only acting on the protons and neutrons as separate groups so we will get separate spectra for each type of nucleon. We assume that the nuclear potential is spherically symmetric so the wave functions can be expressed in terms of spherical harmonics. The solutions can be labelled by two quantum numbers, one enumerating the solutions of the radial wave-function, $n=1,2,3,...$ and the angular momentum $l=0,1,2,3,...$. We will use the spectroscopic nomenclature $l=s,p,d,f,...$ to label the orbital momentum quantum number. </p>
					
					<h1>Background - Extra Information</h1>
					<p>If the potential can be approximated by an harmonic oscillator the energy would be given by the usual
					\[E=\left(2n+l-\frac{1}{2}\right)\omega\]</p>
<p>Unfortunately the actual nuclear potential is neither harmonic nor an infinite well. Since the nuclear force is very short range, the potential it creates should follow the density of nucleons in the nucleus. We will see later which form this density takes and how to measure it. Empirically we can use the following form <br /><span class="math">$$V(r)=-\frac{V_0}{1+e^{(r-r_0)/a}}$$</span><br /> with parameters <span class="math"><em>r</em><sub>0</sub></span> and <span class="math"><em>a</em></span> fitted from data. With this potential we obtain the levels shown in the central part of Figure [fig:levels]. This potential alone is not enough to describe the features that the mass spectrum of nuclides displays. Although the first magic numbers are predicted properly the gap between energy levels do not line up properly to explain the higher magic numbers.</p>
<p>To achieve the agreement with the data we need to consider an addition to the potential: the spin-orbit coupling. In the hydrogen atom electron energy levels the interaction caused by the spin-orbit term in the potential is responsible for the hydrogen fine structure. In the hydrogen case it is not a large effect. In the case of the shell model of the nucleus the effect is larger and does not only creates a splitting but actually reorders shells of different <span class="math"><em>n</em>.<em>l</em></span> quantum numbers, which places the gabs in the energy levels at the right place to explain the magic numbers. The spin-orbit coupling term is given by <br /><span class="math">$$V_{SO}=V_{ls}(r)\left&lt;\vec{l}\cdot\vec{s}\right&gt;$$</span><br /> We can calculate the expectation value of the expectation value of <span class="math"><em>l⃗</em> ⋅ <em>s⃗</em></span> as a function of the eigenvalues of the total angular momentum <span class="math"><em>j</em></span>: <br /><span class="math">$$j(j+1)=\left&lt;\vec{j}^2\right&gt;=\left&lt;(\vec{l}+\vec{s})^2\right&gt;
=
\left&lt;\vec{l}^2+2\vec{l}\cdot\vec{s}+\vec{s}^2\right&gt;
=l(l+1)+s(s+1)+2\left&lt;\vec{l}\cdot\vec{s}\right&gt;$$</span><br /> <br /><span class="math">$$\Rightarrow
\left&lt;\vec{l}\cdot\vec{s}\right&gt;=\frac{j(j+1)-l(l+1)-s(s+1)}{2}$$</span><br /> according to the rules of angular momentum addition the possible values of <span class="math"><em>j</em></span> are either <span class="math"><em>l</em> + 1/2</span> of <span class="math"><em>l</em> − 1/2</span> so we get <br /><span class="math">$$\left&lt;\vec{l}\cdot\vec{s}\right&gt;=\left\{\begin{array}{rcc}
l/2&amp;\mbox{for}&amp; j=l+1/2\\
-(l+1)/2&amp;\mbox{for}&amp; j=l-1/2
\end{array}\right.$$</span><br /> As for the hydrogen atom, we can now label the levels with <span class="math"><em>n</em>, <em>l</em></span> and <span class="math"><em>j</em></span>. The quantum number <span class="math"><em>l</em></span> determines the parity of the state. The energy split between the two <span class="math"><em>j</em></span> levels is given by <br /><span class="math">$$\Delta E_{SO,ls}=\left&lt;V_{ls}(r) \vec{l}\cdot\vec{s}\right&gt;=
\left(\frac{l}{2}-\frac{-(l+1)}{2}\right)=\left&lt;V_{ls}(r)\right&gt;\frac{2l+1}{2}$$</span><br /> We find experimentally that the coefficient <span class="math">$\left&lt;V_{ls}(r)\right&gt;$</span> is negative so that unlike for the electron levels in the hydrogen the energy level with the higher value of <span class="math"><em>j</em></span> is the lower lying one. The result of including this contribution is shown on the right of Figure [fig:levels] and result in splits between levels consistent with the magic numbers.</p>
<p>In practice the proton and neutron potentials can have slightly different shapes resulting in small differences in the ordering of the shells within a band, but not affecting the magic numbers, see Figure [fig:pnlevels].</p>
				</div>
			</div>

		<div class='buttons'>
			<form>
				<div class='form-group row'>
					<label for="numProtons" class='col-xs-4 col-form-label'>Number of Protons</label>
					<div class='col-xs-8'>
						<input type='text' name='numProtons' id='numProtons' class='form-control'>
					</div>
				</div>

				<div class='form-group row'>
					<label for="numNeutrons" class='col-xs-4 col-form-label'>Number of Neutrons</label>
					<div class='col-xs-8'>
						<input type='text' name='numNeutrons' id='numNeutrons' class='form-control'>
					</div>
				</div>
			</form>
		</div>
		</div>

		<div class='container'>
		<div class='row'>
		<div class='myimg col-md-6'>

			<object id='protons' type='image/svg+xml' data='./protons-thin.svg' width="100%">
			</object>

		</div>
		<div class='myimg col-md-6'>

			<object id='neutrons' type='image/svg+xml' data='./neutrons-thin.svg' width="100%">
			</object>

		</div>
		</div>
		</div>
	
		<footer>
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js" integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY" crossorigin="anonymous"></script>
			<script src='./shells.js'></script>
			<script type="text/javascript" async src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js" integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB" crossorigin="anonymous"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
		</footer>
		</div>
	</body>

</html>
